### ISSUE TITLE
New GitHub Terms of Service

### ISSUE THREAD

**Issue by howderek** [OSSHealth/HealthIndicators#12] opened 2017-02-08 17:32 UTC
GitHub is [in the process](https://github.com/blog/2314-new-github-terms-of-service) of updating their terms of service. In [the new ToS](https://help.github.com/articles/github-terms-of-service-draft/) they require research done by scraping GitHub data to be open-access. We are not currently scraping GitHub data but may need to in the future.

Quote:

> You may scrape the website for the following reasons:
> 
> Researchers may scrape public, non-personal information from GitHub for academic research purposes, only if any publications resulting from that research are open access.

Is this okay for us?

**Comment by germonprez** [comment] 2017-02-08 17:44
I commented on Georg's issue (same issue). Shouldn't be a problem for us.

**Comment by GeorgLink** [comment] 2017-02-08 17:47
Hi @howderek, Great minds think alike :+1: 

Issue duplicate of #11

**Closed as completed by GeorgLink** 2017-02-08 17:47 UTC
Labels: duplicate
